// <auto-generated />
using System;
using CrystaLearn.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrystaLearn.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202202840_AddProviderStatusProviderParentId")]
    partial class AddProviderStatusProviderParentId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CrystaLearn")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrystaLearn.Core.Models.Attachments.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasKey("Id", "Kind");

                    b.ToTable("Attachments", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Chatbot.SystemPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromptKind")
                        .IsUnique();

                    b.ToTable("SystemPrompts", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BadgeSystemUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("CrystaPrograms", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaProgramSyncModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CrystaProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModuleType")
                        .HasColumnType("integer");

                    b.Property<string>("SyncConfig")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CrystaProgramId");

                    b.HasIndex("ModuleType");

                    b.ToTable("CrystaProgramSyncModules", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("AreaPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToText")
                        .HasColumnType("text");

                    b.Property<int>("AttachmentsCount")
                        .HasColumnType("integer");

                    b.Property<string>("BoardColumn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("BoardColumnDone")
                        .HasColumnType("boolean");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ChangedById")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CompletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("CompletedByText")
                        .HasColumnType("text");

                    b.Property<double?>("CompletedWork")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("CreatedById1")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedFromRevisionId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CrystaProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomFields")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionHtml")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IterationId")
                        .HasColumnType("uuid");

                    b.Property<string>("IterationPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Links")
                        .HasColumnType("text");

                    b.Property<double?>("OriginalEstimate")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderParentId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderStatus")
                        .HasColumnType("text");

                    b.Property<string>("ProviderTaskId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderTaskUrl")
                        .HasColumnType("text");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Relations")
                        .HasColumnType("text");

                    b.Property<double?>("RemainingWork")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("ResolvedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevisedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("StateChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<double?>("StoryPoints")
                        .HasColumnType("double precision");

                    b.Property<string>("SystemFields")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("TaskAssignDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TaskCreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TaskDoneDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkItemType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("ChangedDate");

                    b.HasIndex("CompletedById");

                    b.HasIndex("CreatedById1");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("CrystaProgramId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProviderTaskId");

                    b.HasIndex("State");

                    b.ToTable("CrystaTasks", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaTaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CommentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CrystaProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrystaTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("EditedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EditedById")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("EditedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormattedText")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderCommentId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderCommentUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProviderTaskId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<string>("Reactions")
                        .HasColumnType("text");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Visibility")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("CrystaProgramId");

                    b.HasIndex("CrystaTaskId");

                    b.HasIndex("ProviderTaskId");

                    b.HasIndex("UserId");

                    b.ToTable("CrystaTaskComments", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaTaskRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("AreaPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToText")
                        .HasColumnType("text");

                    b.Property<int>("AttachmentsCount")
                        .HasColumnType("integer");

                    b.Property<string>("BoardColumn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("BoardColumnDone")
                        .HasColumnType("boolean");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ChangedById")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CompletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("CompletedByText")
                        .HasColumnType("text");

                    b.Property<double?>("CompletedWork")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByIdString")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreatedByText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedFromRevisionId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CrystaProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrystaTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomFields")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionHtml")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IterationId")
                        .HasColumnType("uuid");

                    b.Property<string>("IterationPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Links")
                        .HasColumnType("text");

                    b.Property<double?>("OriginalEstimate")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderTaskId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderTaskUrl")
                        .HasColumnType("text");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Relations")
                        .HasColumnType("text");

                    b.Property<double?>("RemainingWork")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("ResolvedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevisedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RevisionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Severity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("StateChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<double?>("StoryPoints")
                        .HasColumnType("double precision");

                    b.Property<string>("SystemFields")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("TaskAssignDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TaskCreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TaskDoneDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkItemType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("ChangedDate");

                    b.HasIndex("CompletedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("CrystaProgramId");

                    b.HasIndex("CrystaTaskId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProviderTaskId");

                    b.HasIndex("Revision");

                    b.HasIndex("State");

                    b.ToTable("CrystaTaskRevisions", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaTaskUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttachmentChange")
                        .HasColumnType("text");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ChangedById")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedPropertiesJson")
                        .HasColumnType("text");

                    b.Property<string>("CommentText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CrystaProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrystaTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("FieldDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsWorkItemFieldChange")
                        .HasColumnType("boolean");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderTaskId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderUpdateId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<string>("RelationChange")
                        .HasColumnType("text");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedDate");

                    b.HasIndex("CrystaProgramId");

                    b.HasIndex("CrystaTaskId");

                    b.HasIndex("ProviderTaskId");

                    b.HasIndex("Revision");

                    b.HasIndex("UserId");

                    b.ToTable("CrystaTaskUpdates", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", "CrystaLearn");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ff71671-a1d6-5f97-abb9-d87d7b47d6e7"),
                            ConcurrencyStamp = "8ff71671-a1d6-5f97-abb9-d87d7b47d6e7",
                            Name = "s-admin",
                            NormalizedName = "S-ADMIN"
                        },
                        new
                        {
                            Id = new Guid("9ff71672-a1d5-4f97-abb7-d87d6b47d5e8"),
                            ConcurrencyStamp = "9ff71672-a1d5-4f97-abb7-d87d6b47d5e8",
                            Name = "demo",
                            NormalizedName = "DEMO"
                        });
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "ClaimType", "ClaimValue");

                    b.ToTable("RoleClaims", "CrystaLearn");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "mx-p-s",
                            ClaimValue = "-1",
                            RoleId = new Guid("8ff71671-a1d6-5f97-abb9-d87d7b47d6e7")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "feat",
                            ClaimValue = "3.0",
                            RoleId = new Guid("9ff71672-a1d5-4f97-abb7-d87d6b47d5e8")
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "feat",
                            ClaimValue = "3.1",
                            RoleId = new Guid("9ff71672-a1d5-4f97-abb7-d87d6b47d5e8")
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "feat",
                            ClaimValue = "4.0",
                            RoleId = new Guid("9ff71672-a1d5-4f97-abb7-d87d6b47d5e8")
                        });
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ElevatedAccessTokenRequestedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EmailTokenRequestedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("HasProfilePicture")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("OtpRequestedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PhoneNumberTokenRequestedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResetPasswordTokenRequestedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("TwoFactorTokenRequestedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("\"PhoneNumber\" IS NOT NULL");

                    b.ToTable("Users", "CrystaLearn");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ff71671-a1d6-4f97-abb9-d87d7b47d6e7"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTimeOffset(new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ConcurrencyStamp = "315e1a26-5b3a-4544-8e91-2760cd28e231",
                            Email = "test@bitplatform.dev",
                            EmailConfirmed = true,
                            EmailTokenRequestedOn = new DateTimeOffset(new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FullName = "CrystaLearn test account",
                            Gender = 0,
                            HasProfilePicture = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "TEST@BITPLATFORM.DEV",
                            NormalizedUserName = "TEST",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0v3wxkdWtMkHA3Pp5/JfS+42/Qto9G05p2mta6dncSK37hPxEHa3PGE4aqN30Aag==",
                            PhoneNumber = "+31684207362",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "959ff4a9-4b07-4cc1-8141-c5fc033daf83",
                            TwoFactorEnabled = false,
                            UserName = "test"
                        });
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClaimType", "ClaimValue");

                    b.ToTable("UserClaims", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId", "UserId")
                        .IsUnique();

                    b.ToTable("UserRoles", "CrystaLearn");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("8ff71671-a1d6-4f97-abb9-d87d7b47d6e7"),
                            RoleId = new Guid("8ff71671-a1d6-5f97-abb9-d87d7b47d6e7")
                        });
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text");

                    b.Property<string>("CultureName")
                        .HasColumnType("text");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text");

                    b.Property<string>("IP")
                        .HasColumnType("text");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("PlatformType")
                        .HasColumnType("integer");

                    b.Property<bool>("Privileged")
                        .HasColumnType("boolean");

                    b.Property<long?>("RenewedOn")
                        .HasColumnType("bigint");

                    b.Property<string>("SignalRConnectionId")
                        .HasColumnType("text");

                    b.Property<long>("StartedOn")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.WebAuthnCredential", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AttestationClientDataJson")
                        .HasColumnType("bytea");

                    b.Property<string>("AttestationFormat")
                        .HasColumnType("text");

                    b.Property<byte[]>("AttestationObject")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsBackedUp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBackupEligible")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("RegDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<int[]>("Transports")
                        .HasColumnType("integer[]");

                    b.Property<byte[]>("UserHandle")
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WebAuthnCredential", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.PushNotification.PushNotificationSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<long>("ExpirationTime")
                        .HasColumnType("bigint");

                    b.Property<string>("P256dh")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PushChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RenewedOn")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserSessionId")
                        .IsUnique()
                        .HasFilter("\"UserSessionId\" IS NOT NULL");

                    b.ToTable("PushNotificationSubscriptions", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Server.Api.Models.Identity.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Server.Api.Models.Identity.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "CrystaLearn");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireCounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpireAt");

                    b.HasIndex("Key", "Value");

                    b.ToTable("HangfireCounter", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireHash", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Field")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key", "Field");

                    b.HasIndex("ExpireAt");

                    b.ToTable("HangfireHash", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvocationData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("StateId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ExpireAt");

                    b.HasIndex("StateId");

                    b.HasIndex("StateName");

                    b.ToTable("HangfireJob", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireJobParameter", b =>
                {
                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("JobId", "Name");

                    b.ToTable("HangfireJobParameter", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireList", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key", "Position");

                    b.HasIndex("ExpireAt");

                    b.ToTable("HangfireList", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireLock", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HangfireLock", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireQueuedJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FetchedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Queue", "FetchedAt");

                    b.ToTable("HangfireQueuedJob", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireServer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("Heartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Queues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkerCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Heartbeat");

                    b.ToTable("HangfireServer", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireSet", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("Key", "Value");

                    b.HasIndex("ExpireAt");

                    b.HasIndex("Key", "Score");

                    b.ToTable("HangfireSet", "jobs");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("HangfireState", "jobs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "CrystaLearn");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaProgramSyncModule", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Crysta.CrystaProgram", "CrystaProgram")
                        .WithMany()
                        .HasForeignKey("CrystaProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "SyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaProgramSyncModuleId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaProgramSyncModuleId");

                            b1.ToTable("CrystaProgramSyncModules", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaProgramSyncModuleId");
                        });

                    b.Navigation("CrystaProgram");

                    b.Navigation("SyncInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaTask", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedById");

                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById1");

                    b.HasOne("CrystaLearn.Core.Models.Crysta.CrystaProgram", "CrystaProgram")
                        .WithMany()
                        .HasForeignKey("CrystaProgramId");

                    b.HasOne("CrystaLearn.Core.Models.Crysta.CrystaTask", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "CommentsSyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaTaskId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaTaskId");

                            b1.ToTable("CrystaTasks", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaTaskId");
                        });

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "RevisionsSyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaTaskId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaTaskId");

                            b1.ToTable("CrystaTasks", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaTaskId");
                        });

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "UpdatesSyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaTaskId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaTaskId");

                            b1.ToTable("CrystaTasks", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaTaskId");
                        });

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "WorkItemSyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaTaskId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaTaskId");

                            b1.ToTable("CrystaTasks", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaTaskId");
                        });

                    b.Navigation("AssignedTo");

                    b.Navigation("CommentsSyncInfo")
                        .IsRequired();

                    b.Navigation("CompletedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("CrystaProgram");

                    b.Navigation("Parent");

                    b.Navigation("RevisionsSyncInfo")
                        .IsRequired();

                    b.Navigation("UpdatesSyncInfo")
                        .IsRequired();

                    b.Navigation("WorkItemSyncInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaTaskComment", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Crysta.CrystaProgram", "CrystaProgram")
                        .WithMany()
                        .HasForeignKey("CrystaProgramId");

                    b.HasOne("CrystaLearn.Core.Models.Crysta.CrystaTask", "CrystaTask")
                        .WithMany()
                        .HasForeignKey("CrystaTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "SyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaTaskCommentId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaTaskCommentId");

                            b1.ToTable("CrystaTaskComments", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaTaskCommentId");
                        });

                    b.Navigation("CrystaProgram");

                    b.Navigation("CrystaTask");

                    b.Navigation("SyncInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaTaskRevision", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedById");

                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CrystaLearn.Core.Models.Crysta.CrystaProgram", "CrystaProgram")
                        .WithMany()
                        .HasForeignKey("CrystaProgramId");

                    b.HasOne("CrystaLearn.Core.Models.Crysta.CrystaTask", "CrystaTask")
                        .WithMany()
                        .HasForeignKey("CrystaTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "CommentsSyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaTaskRevisionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaTaskRevisionId");

                            b1.ToTable("CrystaTaskRevisions", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaTaskRevisionId");
                        });

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "RevisionsSyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaTaskRevisionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaTaskRevisionId");

                            b1.ToTable("CrystaTaskRevisions", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaTaskRevisionId");
                        });

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "UpdatesSyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaTaskRevisionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaTaskRevisionId");

                            b1.ToTable("CrystaTaskRevisions", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaTaskRevisionId");
                        });

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "WorkItemSyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaTaskRevisionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaTaskRevisionId");

                            b1.ToTable("CrystaTaskRevisions", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaTaskRevisionId");
                        });

                    b.Navigation("AssignedTo");

                    b.Navigation("CommentsSyncInfo")
                        .IsRequired();

                    b.Navigation("CompletedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("CrystaProgram");

                    b.Navigation("CrystaTask");

                    b.Navigation("RevisionsSyncInfo")
                        .IsRequired();

                    b.Navigation("UpdatesSyncInfo")
                        .IsRequired();

                    b.Navigation("WorkItemSyncInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Crysta.CrystaTaskUpdate", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Crysta.CrystaProgram", "CrystaProgram")
                        .WithMany()
                        .HasForeignKey("CrystaProgramId");

                    b.HasOne("CrystaLearn.Core.Models.Crysta.CrystaTask", "CrystaTask")
                        .WithMany()
                        .HasForeignKey("CrystaTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsOne("CrystaLearn.Core.Models.Crysta.SyncInfo", "SyncInfo", b1 =>
                        {
                            b1.Property<Guid>("CrystaTaskUpdateId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("LastSyncDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastSyncOffset")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<DateTimeOffset?>("SyncEndDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SyncGroup")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("SyncId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("SyncStartDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("SyncStatus")
                                .HasColumnType("integer");

                            b1.HasKey("CrystaTaskUpdateId");

                            b1.ToTable("CrystaTaskUpdates", "CrystaLearn");

                            b1.WithOwner()
                                .HasForeignKey("CrystaTaskUpdateId");
                        });

                    b.Navigation("CrystaProgram");

                    b.Navigation("CrystaTask");

                    b.Navigation("SyncInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.RoleClaim", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Identity.Role", "Role")
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.UserClaim", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.UserRole", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Identity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.UserSession", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.WebAuthnCredential", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "User")
                        .WithMany("WebAuthnCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.PushNotification.PushNotificationSubscription", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Identity.UserSession", "UserSession")
                        .WithOne("PushNotificationSubscription")
                        .HasForeignKey("CrystaLearn.Core.Models.PushNotification.PushNotificationSubscription", "UserSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("CrystaLearn.Server.Api.Models.Identity.UserLogin", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrystaLearn.Server.Api.Models.Identity.UserToken", b =>
                {
                    b.HasOne("CrystaLearn.Core.Models.Identity.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireJob", b =>
                {
                    b.HasOne("Hangfire.EntityFrameworkCore.HangfireState", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireJobParameter", b =>
                {
                    b.HasOne("Hangfire.EntityFrameworkCore.HangfireJob", "Job")
                        .WithMany("Parameters")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireQueuedJob", b =>
                {
                    b.HasOne("Hangfire.EntityFrameworkCore.HangfireJob", "Job")
                        .WithMany("QueuedJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireState", b =>
                {
                    b.HasOne("Hangfire.EntityFrameworkCore.HangfireJob", "Job")
                        .WithMany("States")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.Role", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Roles");

                    b.Navigation("Sessions");

                    b.Navigation("Tokens");

                    b.Navigation("WebAuthnCredentials");
                });

            modelBuilder.Entity("CrystaLearn.Core.Models.Identity.UserSession", b =>
                {
                    b.Navigation("PushNotificationSubscription");
                });

            modelBuilder.Entity("Hangfire.EntityFrameworkCore.HangfireJob", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("QueuedJobs");

                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
