name: $(Major).$(Minor).$(Patch).$(Build.BuildId)

pr:
  branches:
    include:
      - develop

variables:
  DOCKER_REGISTRY: 'registry.hamdocker.ir'
  IMAGE_NAME: 'cslearn'

pool:
  name: "Azure Pipelines"
  vmImage: 'ubuntu-24.04'

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    variables:
      WebAppRender.BlazorMode: 'BlazorWebAssembly'
      WebAppRender.PrerenderEnabled: true
    jobs:
      - job: Build
        displayName: Build & Push
        steps:
          - task: UseDotNet@2
            displayName: 'Setup .NET'
            inputs:
              packageType: 'sdk'
              useGlobalJson: true
              workingDirectory: '.'

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSource: 'spec'
              versionSpec: '23.x'
          - task: Bash@3
            displayName: 'Install wasm'
            inputs:
              targetType: 'inline'
              script: |
                cd src && dotnet workload install wasm-tools

          - task: Bash@3
            displayName: 'Generate CSS/JS files'
            inputs:
              targetType: 'inline'
              script: |
                dotnet build src/Client/CrystaLearn.Client.Core/CrystaLearn.Client.Core.csproj -t:BeforeBuildTasks --no-restore -c Release
                dotnet build src/Client/CrystaLearn.Client.Web/CrystaLearn.Client.Web.csproj -t:BeforeBuildTasks --no-restore -c Release
          - task: Bash@3
            displayName: 'Build Server Project'
            inputs:
              targetType: 'inline'
              script: |
                cd src/Server/CrystaLearn.Server.Web
                dotnet publish CrystaLearn.Server.Web.csproj -c Release --self-contained -r linux-x64 -o $(Build.ArtifactStagingDirectory)/publish -p:version=$(Major).$(Minor).$(Patch).$(Build.BuildId)
          
          - task: CopyFiles@2
            displayName: 'Copy Docker file to ouput directory'
            inputs:
              SourceFolder: '.'
              Contents: 'Dockerfile'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
          