name: $(Major).$(Minor).$(Patch).$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

jobs:
- job: build_windows
  displayName: 'CI build - Windows'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Setup .NET'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
      workingDirectory: '.'

  - task: PowerShell@2
    displayName: 'Install wasm workload'
    inputs:
      targetType: 'inline'
      script: dotnet workload install wasm-tools

  - task: PowerShell@2
    displayName: 'Install dotnet-ef'
    inputs:
      targetType: 'inline'
      script: |
        dotnet tool install --global dotnet-ef --version 9.*
        dotnet tool restore
        dotnet restore
      workingDirectory: 'src/Core/CrystaLearn.Core'

  - task: PowerShell@2
    displayName: 'Run ef migrations'
    inputs:
      targetType: 'inline'
      script: | 
        dotnet ef migrations bundle --self-contained -r win-x64 -v `
        --project src/Core/CrystaLearn.Core/CrystaLearn.Core.csproj `
        --startup-project src/Server/CrystaLearn.Server.Api/CrystaLearn.Server.Api.csproj 
      workingDirectory: '.'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'src/Core/CrystaLearn.Core'
      Contents: |
        environments.json
        environments.release.json
      TargetFolder: 'src/Core/CrystaLearn.Core/migrations-bundle'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'src/Core/CrystaLearn.Core'
      Contents: 'efbundle.exe'
      TargetFolder: 'src/Core/CrystaLearn.Core/migrations-bundle'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'src/Core/CrystaLearn.Core/migrations-bundle'
      ArtifactName: 'migrations-bundle-ubuntu'
      publishLocation: 'Container'
