name: CrystallineSociety CI

# https://bitplatform.dev/templates/dev-ops

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:

  build_blazor_server:
    name: build blazor
    runs-on: ubuntu-22.04

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/CrystallineSociety/global.json

    - uses: actions/setup-node@v3
      with:
        node-version: 20.3.0

    - name: Install wasm and maui
      run:  cd src && dotnet workload install maui-android wasm-tools wasm-experimental

    - name: Install Android Sdk platform tools
      run: ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools"
          
    - name: Build
      run: dotnet build src/CrystallineSociety/CrystallineSociety.sln -c Release -p:EnableWindowsTargeting=true
